version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          name: "Install dependency"
          command: npm install

      - run:
          name: "Code Linting"
          command: npm run lint


  test:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          name: "Install dependency"
          command: npm install

      - run:
          name: "Run tests"
          command: npm run test

  analyze:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          name: "Install dependency"
          command: npm audit

workflows:
  integration_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test

